{
  "deploy": {
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10,
    "buildCommand": "",
    "startCommand": "python bot.py"
  },
  "variables": {
    "TELEGRAM_BOT_TOKEN": "7649664953:AAH7kGKJHV53UT-nvtxTsW8mOWY0OXrhsvA"
  },
  "healthcheckPath": "/",
  "healthcheckTimeout": 100
}
